import "bootstrap/dist/css/bootstrap.min.css"
import "@/app/styles/custom.css" // 添加這一行
import { useEffect } from "react"

import "./globals.css"
import { MetadataRoute } from "next/server"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}) {
  useEffect(() => {
    // Add your useEffect logic here if needed
  }, [])

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}